apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-workflows
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/teneusz/argo-workflow-demo.git
    targetRevision: master
    path: apps/argo-workflow
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-workflows
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

      apiVersion: argoproj.io/v1alpha1
---
# kind: Application
# metadata:
#   name: demo-workflow-config
#   namespace: argo-workflows
# spec:
#   project: default
#   source:
#     repoURL: https://github.com/teneusz/argo-workflow-demo.git
#     targetRevision: master
#     path: apps/demo
#   destination:
#     server: https://kubernetes.default.svc
#     namespace: argo-workflows
#   syncPolicy:
#     automated:
#       prune: true
#       selfHeal: true
