{{- foreach app in .Values.apps}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{app.name}}
  namespace: argocd
spec:
  project: default
  source:
    repoURL: {{app.source.repoURL}}
    targetRevision: {{app.source.targetRevision}}
    path: {{app.source.path}}
  destination:
    server: {{app.destination.server | default .Values.defaults.destination.server}}
    namespace: {{app.destination.namespace | default .Values.defaults.destination.namespace}}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
{{- end}}
